### ISSUE TITLE
Executavel do Linux não abre o VSCode

### ISSUE THREAD

**Issue by anaalicefig** [diego3g/youtube-challenge-electron-tray#18]
Consigo adicionar o projeto e remover, mas na hora que clico para abrir o VSCode não abre.

**Comment by RavcRodrigo** [comment]
No seu terminal rodando o comando: 
`code pasta-projeto`
ele está funcionando?

**Comment by rodrigocananea** [comment]
> Consigo adicionar o projeto e remover, mas na hora que clico para abrir o VSCode não abre.

No seu terminal rodando o comando:
code pasta-projeto
ele está funcionando?

**Comment by anaalicefig** [comment]
Sim

**Comment by diego3g** [comment]
Parece que a última atualização com o `cross-spawn` deu alguns problemas. Vou dar uma olhada nisso e enviar uma PR logo :)

**Comment by diego3g** [comment]
Podem testar e me dar um feedback no #20 ?
